# Generated by nixos-generate-config on workstation hardware.
# Real values from AMD Ryzen 7 7800X3D + RX 9070 workstation.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  # NixOS root partition (Disk 1 / 1TB NVMe, ~329GB ext4)
  fileSystems."/" =
    { device = "/dev/disk/by-label/vainos";
      fsType = "ext4";
    };

  # XBOOTLDR partition (1GB, holds kernels/initrds for systemd-boot)
  fileSystems."/boot" =
    { device = "/dev/disk/by-label/XBOOTLDR";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  # EFI System Partition (shared with Windows, 100MB — bootloader binary only)
  fileSystems."/efi" =
    { device = "/dev/disk/by-uuid/868C-2901";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  # Windows data partitions (Disk 0 / 4TB NVMe)
  # Mounted by label -- ntfs3 is the native kernel driver (no FUSE)
  # nofail: boot continues even if Windows has partitions locked (hibernate/fast startup)
  fileSystems."/mnt/misc" =
    { device = "/dev/disk/by-label/misc";
      fsType = "ntfs3";
      options = [ "rw" "uid=1000" "gid=100" "dmask=022" "fmask=133" "nofail" ];
    };

  fileSystems."/mnt/media" =
    { device = "/dev/disk/by-label/media";
      fsType = "ntfs3";
      options = [ "rw" "uid=1000" "gid=100" "dmask=022" "fmask=133" "nofail" ];
    };

  fileSystems."/mnt/dev" =
    { device = "/dev/disk/by-label/dev";
      fsType = "ntfs3";
      options = [ "rw" "uid=1000" "gid=100" "dmask=022" "fmask=133" "nofail" ];
    };

  swapDevices = [ ];

  networking.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
